dist: xenial
language: node_js
node_js:
  - "12"

cache:
  - directories:
    - $HOME/.npm
    - .pnpm-store
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r .pnpm-store

before_install:
  - set -e
  - npm i -g pnpm

install:
  - pnpm install --frozen-lockfile --store=.pnpm-store

script:
  - pnpm run it

after_script: set +e

branches:
  only:
    # test branches
    - /^try-/

    # main branches
    - main

notifications:
  email:
    on_success: never

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  fqdn: what.passcod.name
  local_dir: ./www
  on:
    repo: passcod/what
    branch: main
