name = "The Caretaker System"
what = "A “addon” contribution system for open software projects that trades higher trust for less effort on the maintainers parts, allowing projects to survive and grow even if the creator is mostly checked out."
how = "I'm writing the text of the system and making a website that can be linked to for contributors to quickly get information about what they can do and how, in addition to the long form description."
with = ["words", "jekyll"]
started = "2020-05-16"
now = "Halfway done with the initial draft. Renamed from model to system."
where = [
  "https://caretaker.passcod.name",
  "https://github.com/passcod/caretaker",
  "https://nanowrimo.org/participants/passcod/projects/the-caretaker-model",
]
media = [
  "https://twitter.com/passcod/status/1264438548620443649",
  "https://twitter.com/passcod/status/1261450928915243009",
]
