name = "defnew"
what = "A tool kit for manipulating C ABI like data structures and interacting with libc... *on the shell*!"
how = "Copious amounts of bad Rust... I'm not going for pretty, as this is a tool that I want for me, and not really going for public consumption, though this will be readily usable out of the box once done."
with = ["words", "lexpr crate", "libc crate", "unholy parsing of rustdoc output", "clap 3"]
started = "2020-06-01"
now = "Starting on the penultimate main tool, which will make it possible to call arbitrary libc functions from the shell."
where = "https://github.com/passcod/defnew"
media = [
  "",
]
