what = "“Crackfic-taken-seriously in the form of an open-source project readme,” the configuration library."
how = "It started as a redesign of config-rs. Then I started adding stuff. Then I abandoned all pretense of this being at all realistic and started just going wild. Then I figured I might as well make document it all so thoroughly and consistently it could actually plausibly have an implementation. That's where I'm at. Maybe when I'm done I'll write the code. Or maybe not."
with = ["rust", "markdown", "nightmares"]
where = "github:passcod/figleaf"
started = "2019-11-08"
now = "Starting on the configuration sources section"
media = [
  "https://twitter.com/passcod/status/1192727580832493569",
  "https://twitter.com/passcod/status/1192966242321092609",
  "https://twitter.com/passcod/status/1193804512621817857",
  "https://twitter.com/passcod/status/1194146075000487936",
  "https://twitter.com/passcod/status/1195532802998951937",
  "https://twitter.com/passcod/status/1195550437602017281",
]
