what = "A rewrite of rogare in Rust"
how = "I want to get locales in there as well as voice, and the Ruby implementation just isn't solid enough for this kind of thing. There’s also a lot of cruft in rogare I’d like to avoid, bringing over only the Good Parts."
with = ["Rust", "serenity (discord client)", "config-rs", "Fluent (l10n)", "diesel (postgres initially)"]
where = "github:storily/garrire"
started = "2019-07-07"
now = "While the serenity-based instance is in production, the dawn trial didn't really go anywhere. I now want to investigate a different approach entirely based on translating the API to http calls to a local server, and implementing the actual functionality in scripts or adhoc servers routed via nginx instead of a monolithic / custom plugin system approach."
media = [
  "https://twitter.com/passcod/status/1248854499772391425",
  "https://twitter.com/passcod/status/1148485443060523008",
  "https://twitter.com/passcod/status/1175754128938565632",
  "https://twitter.com/passcod/status/1179950538764382209",
  "https://twitter.com/passcod/status/1181208515509018624",
  "https://twitter.com/passcod/status/1182937660194582529",
  "https://twitter.com/passcod/status/1183000979433607168",
  "https://twitter.com/passcod/status/1184024184399073280",
  "https://twitter.com/passcod/status/1186166780026216449",
  "https://twitter.com/passcod/status/1185371114739884038",
  "https://twitter.com/passcod/status/1187727565286453254",
  "https://twitter.com/passcod/status/1189463018280640512",
  "https://twitter.com/passcod/status/1189516315402260481",
  "https://twitter.com/passcod/status/1189522641587097600",
  "https://twitter.com/passcod/status/1189846421194723330",
  "https://twitter.com/passcod/status/1190034675051499525",
  "https://twitter.com/passcod/status/1191663848182317056",
]
