what = "A rewrite of rogare in Rust"
how = "I want to get locales in there as well as voice, and the Ruby implementation just isn't solid enough for this kind of thing. There’s also a lot of cruft in rogare I’d like to avoid, bringing over only the Good Parts."
with = ["Rust", "serenity (discord client)", "config-rs", "Fluent (l10n)", "diesel (postgres initially)"]
where = "github:storily/garrire"
started = "2019-07-07"
now = "Pondering a refactor dumping the serenity framework for a setup where the entire command space is a single LALRPOP grammar, to both simplify development and add more power, such as typo resolution and expressive aliasing."
media = [
  "https://twitter.com/passcod/status/1148485443060523008",
]
