what = "Setting up an IKEA table I’d ordered a while ago."
how = "It’s an IKEA thing. How hard can it be? <i>cue laugh track</i>"
now = "I’ve got the table done, and one chair, and most of the pieces for the rest, but phew! I’ll finish the next day."
with = ["jokkmokk", "lots of swearing"]
started = "2019-04-29"
media = "https://twitter.com/passcod/status/1122743248907149313"
