what = "Keycasting: the return! Metal edition"
how = "I’m very much not doing my own metal casting, thank you. Instead I’ll be navigating casting wax and foundries for a very small run of a very small piece. From cursory research, I ideally want to cast some copies in beeswax, send that to a foundry that can pour Nickel Silver (or brass as a fallback), and then get my keys!"
with = ["this blasted key", "small local foundries", "idk yet"]
started = "2019-06-29"
media = [
  "https://what.passcod.name/#keycasting",
  "https://twitter.com/passcod/status/1144847407378624517",
]
