name = "notify 5.0"
what = "The next release of the Notify file monitor library."
how = "I’m refactoring: the event system (using the new system from the next branch and by this same act unifying the raw and debounced events), configuration (introducing runtime config, moving some notify features to opt-in instead of being always on), some naming (“raw” mode is not very descriptive in hindsight, so I’m calling it “immediate” mode now)."
with = ["rust"]
where = "github:passcod/notify"
started = "2019-03-28"
now = "Converted the bulk of the library code, onto test code."
media = [
  "https://twitter.com/passcod/status/1119943511095136257",
  "https://twitter.com/passcod/status/1124936733190045696",
  "https://twitter.com/passcod/status/1135517583807922176",
  "https://twitter.com/passcod/status/1135828060186431488",
]
