name = "percy w.: witch"
what = "A Harry Potter fanfic centered around Percy Weasley"
how = "A bit crack-taken-seriously, a bit riff on badass/lazy tropes, a bit inspired by Agnes Nutter: Witch, a bit taken with the utter madness of some Hobbit fics I’ve read recently. It has the potential to be fairly funny even if I’m being a downer and writing super-sad character development up front (because Percy was a child during the wizarding war, and that can’t have been all fucking sunny days and happy occasions)."
with = ["words", "ao3"]
started = "2019-02-26"
now = "Writing chapter 3."
