what = "A browser extension companion to track and manage the fanfic I read."
how = "The idea so far is to track both what I want to read, what I’m reading, following, etc, all with a minimal amount of interactions. Simply visiting a fanfic page should track it, and some work with the Intersection Observer API should yield a pretty accurate detection of actively reading a fic vs just having it open or looking through it without really reading."
with = ["firefox", "web-ext", "es modules", "automerge", "crdt"]
started = "2019-04-19"
now = "Scaffolding the UI and trying to figure out the data layer."
media = [
  "https://twitter.com/passcod/status/1119236020954755072",
  "https://twitter.com/passcod/status/1121013733533175809",
  "https://twitter.com/passcod/status/1121754299850084352",
]
