what = "Putting some new fabric on the seat cushions"
how = "I bought six chairs for pretty cheap, mostly because they're dirty and uncleanable. But the chairs themselves are okay, if not very good quality (probably made from recycled wood originally). So I'm going to reupholster them, made sure they’re solid, and perhaps paint some of them white too."
with = ["chairs", "some nice red lined polyesther fabric", "idk, staples or something", "white paint sampler pot: mt aspiring by dulux"]
started = "2019-04-11"
now = "I bought the fabric, now to find the stapler and try it on one chair."
media = []
