what = "A store for queues"
how = "I sketched this over a few days and the readme has more but I’m not entirely sure where its heart lies yet. It’s a low-level store focused around medium-scale queues with some added advanced features. Nothing too terribly exciting, but is being written to enable more stuff higher up."
with = ["rust", "sled", "wasm"]
where = "github:passcod/storq"
started = "2019-06-15"
media = [
  "https://twitter.com/passcod/status/1176810960520003585",
  "https://twitter.com/passcod/status/1177809141491847168",
  "https://twitter.com/passcod/status/1178150528196517888",
  "https://twitter.com/passcod/status/1178275070013132800",
  "https://twitter.com/wasmerio/status/1178399426936627200",
  "https://twitter.com/passcod/status/1179335228923535360",
  "https://twitter.com/passcod/status/1179950538764382209",
  "https://twitter.com/passcod/status/1180370658183696384",
]
