what = "A utility to swap two files atomically, or as close as"
how = "On Linux 3.15+, the renameat2 call. On macOS, the exchangedata call. On Windows that supports Transactional NTFS, that. On WSL2 (potentially), the renameat2 call. On other platforms, a fallback method using memory mapping for small files, hardlinks otherwise, and renaming as a last resort.<br>Several other tiny tools using renameat2 exist, but I have not found one that attempts to be cross-platform."
with = ["rust"]
where = "https://github.com/passcod/swp"
started = "2019-05-22"
media = []
