what = "A small tool to show off what I’m working on."
how = "It’s a Node script that creates a small static site from a TOML file. On push of its git repo, a Travis build kicks off, and pushes the result to its gh_pages branch, which updates the site."
with = ["node", "pnpm", "travis", "toml"]
where = "github:passcod/what"
started = "2019-04-27"
now = "If you’re reading this then I must be done or close to it!"
media = [
  "https://twitter.com/passcod/status/1122081844751687681",
]
