what = "A job system for a wonderful world."
how = "This was about building a job system that offers rich workflow potential and excellent monitoring/auditability while also being very lightweight. Scalability and partition-tolerance are secondary concerns at the moment. Inspired by Gearman, but aiming to be a superset."
with = ["rust", "json-rpc", "websocket"]
where = [
  "github:passcod/armstrong",
  "github:passcod/gearbox",
  "github:passcod/gearbox-rs",
]
started = "2018-11-22"
finished = "2020-01-01"
now = "Abandoned."
media = [
  "https://twitter.com/passcod/status/1085658418428276738",
  "https://twitter.com/passcod/status/1086764854550192128",
]
