what = "ls and cat in one tool"
how = "It uses exa to provide ls-like functionality, and if it's passed a file it prints it out instead, so it’s both cat and ls in a single two-letter tool, which makes it more convenient when exploring a filesystem, instead of having to edit the head of the line to swap tool."
with = ["rust", "exa"]
started = "2019-12-10"
finished = "2020-06-03"
media = [
  "https://twitter.com/passcod/status/1267966677003587585",
  "https://twitter.com/passcod/status/1204334618733735936",
]
