what = "A little bit of custom furniture to support four restaurant-style glass hanger racks without damaging anything in my rented appartment."
how = "I designed it over a Saturday, went to buy the supplies that evening, built and assembled it the next day, then spent two evenings painting it."
with = ["plywood", "dressed pine timber", "box of screws", "wood glue", "dulux white mt aspiring sample pot", "excellent tools"]
where = "home"
started = "2019-10-12"
finished = "2019-10-17"
media = [
  "https://twitter.com/passcod/status/1182871117893005313",
  "https://twitter.com/passcod/status/1182937660194582529",
]
