what = "Final installment of the key saga"
how = "In January I ordered key blanks that matched my key from AliExpress, in order to maybe finally be able to either cut my own keys or get them cut."
with = ["this blasted key", "aliexpress", "the local locksmith"]
started = "2020-01-16"
finished = "2020-06-05"
where = [
  "a factory in shenzen",
  "a warehouse in auckland airport where it spent the entire covid lockdown",
  "right here in this town",
]
now = "Keys were cut and tested, all done!"
media = [
  "https://what.passcod.name/#keycasting",
  "https://what.passcod.name/#keycasting-metal",
  "https://twitter.com/passcod/status/1264458817430908929",
]
