what = "A suite of personal archiving tools for tweets."
with = ["rust", "egg-mode", "reqwest", "diesel", "postgres"]
where = "github:passcod/omelette"
started = "2018-12-27"
finished = "2019-01-03"
media = [
  "https://twitter.com/passcod/status/1078147059771822080",
  "https://twitter.com/passcod/status/1078200068879015937",
  "https://twitter.com/passcod/status/1078273937161650177",
  "https://twitter.com/passcod/status/1078630077145862145",
]
