what = "(Roughly) quarterly updates for patrons/sponsors/followers"
how = "Monthly didn't work, Yearly is too long, and I needed something to give financial supporters."
with = ["my poor fingers"]
where = [
  "https://www.patreon.com/posts/spring-2019-31102896",
]
started = "2019-10-20"
finished = "2020-03-03"
now = "Discontinued the entire sponsorship thing, so no need for this lol."
media = [
  "https://twitter.com/passcod/status/1182460264710471680",
]
