name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy
      uses: passcod/github-pages-deploy-action@dev
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: main
        BRANCH: gh-pages
        FOLDER: www
        BUILD_SCRIPT: "pnpm i --production --frozen-lockfile && pnpm run it"
        CNAME: what.passcod.name
